"""Add workflow events table

Revision ID: 002_workflow_events
Revises: 001_initial
Create Date: 2026-01-02

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_workflow_events'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Workflow events table
    op.create_table('workflow_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('decision_id', sa.Integer(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('event_type', sa.Enum(
            'RUN_CREATED', 'RUN_STARTED', 'RUN_COMPLETED', 'RUN_FAILED', 'RUN_CANCELLED',
            'STATE_TRANSITION',
            'TASK_CREATED', 'TASK_STARTED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_RETRYING', 'TASK_SKIPPED',
            'DECISION_CREATED', 'DECISION_UPDATED', 'HUMAN_DECISION_MADE',
            'TOKEN_USAGE_RECORDED', 'COST_ESTIMATED',
            'ERROR_OCCURRED', 'RECOVERY_ATTEMPTED',
            name='workfloweventtype'
        ), nullable=False),
        sa.Column('previous_state', sa.String(length=50), nullable=True),
        sa.Column('new_state', sa.String(length=50), nullable=True),
        sa.Column('actor', sa.String(length=100), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
        sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_created_at'), 'workflow_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_events_decision_id'), 'workflow_events', ['decision_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_id'), 'workflow_events', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_events_run_id'), 'workflow_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_task_id'), 'workflow_events', ['task_id'], unique=False)
    
    # Add relationships to models (back-populates)
    # Note: These are handled in the ORM, not migration
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_workflow_events_task_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_run_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_decision_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_created_at'), table_name='workflow_events')
    op.drop_table('workflow_events')
    # ### end Alembic commands ###
